### ISSUE TITLE
Where to find the Client_ID and Client_Secret

### ISSUE THREAD

**Issue by magomed90** [sipgate/rest-api-examples#2]
Hello,

where do i find the client_id and the client_secret which you defined in npmrc.dist? Everything else than "client_id=sipgate-app-web" gives me an "client not found" and if I use "client_id=sipgate-app-web" I can't redirect to any other page than the sipgate one.

**Comment by gidsi** [comment]
Hey,

you have to create a client yourself, you can find documentation about that here: https://developer.sipgate.io/rest-api/managing-third-party-clients/

Hope that helps :)
